version: '3.1'
services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      BASE_URL: ${BASE_URL}
      LINK_CSS_SELECTOR: ${LINK_CSS_SELECTOR}
      CORRECT_URL_PATTERN: ${CORRECT_URL_PATTERN}
      POLLING_INTERVAL: ${POLLING_INTERVAL}
      DATABASE_PATH: ${DATABASE_PATH}
      ADMIN_ID: ${ADMIN_ID}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_USERNAME: ${BOT_USERNAME}
    volumes:
      - db:/tws-bot/volumes/

volumes:
  db: